# Generated by Django 5.0 on 2023-12-18 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0002_dish_pimage_alter_dish_dishdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Maharashtrian Thali'), (2, 'Punjabi Thali'), (3, 'Chinese'), (3, 'Starter')], default=0, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('did', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='restoapp.dish')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('qty', models.IntegerField(default=1)),
                ('did', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='restoapp.dish')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
