# Generated by Django 5.0 on 2023-12-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0003_dish_cat_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Maharashtrian Thali'), (2, 'Punjabi Thali'), (3, 'Chinese')], verbose_name='category'),
        ),
    ]
