# Generated by Django 5.0 on 2024-01-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0004_alter_dish_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=50)),
                ('umsgs', models.CharField(max_length=200)),
            ],
        ),
    ]
